add git-squash

diff --git a/bash/functions b/bash/functions
--- a/bash/functions
+++ b/bash/functions
@@ -1,2 +1,31 @@
 #!/bin/sh
 
+git-squash() {
+    if [ $# -ne 1 -o "$1" = "-h" ]
+    then
+        echo -e "Usage: git-squash -h | number_of_commits"
+        return 1
+    fi
+
+    if ! [[ ($1 =~ ^[0-9]+$) && ($1 -gt 1) ]]
+    then
+        echo "Number of squashes must be an integer greater than 1"
+        return 1
+    fi
+
+    git log -n $1 || return $?
+
+    echo
+    read -p "Squash these commits? [N/y] "
+    echo
+
+    if ! [[ $REPLY =~ ^[Yy] ]]
+    then
+        echo "Squash aborted"
+        return 2
+    fi
+
+    echo Squashing $1 commits
+    git reset --soft HEAD~$1 &&
+        git commit --edit -m"$(git log --format=%B --reverse HEAD..HEAD@{1})"
+}
